import { defineDocument } from "../define-document";

export const basicInvoiceDefinition = defineDocument({
  id: "basic-invoice",
  version: 1,
  label: "Basic Invoice",
  description: "A basic invoice without line-item arrays or calculated totals.",
  fields: [
    {
      key: "issuerName",
      label: "Issuer name",
      description: "The name of the person or business issuing the invoice.",
      kind: "text",
      required: true,
      placeholder: "Acme Services LLC",
      pdfFieldName: "invoice.issuer_name",
    },
    {
      key: "issuerAddress",
      label: "Issuer address",
      description: "The mailing address of the invoice issuer.",
      kind: "textarea",
      required: true,
      placeholder: "123 Market St, San Francisco, CA",
      pdfFieldName: "invoice.issuer_address",
    },
    {
      key: "customerName",
      label: "Customer name",
      description: "The name of the customer receiving the invoice.",
      kind: "text",
      required: true,
      placeholder: "Globex Corporation",
      pdfFieldName: "invoice.customer_name",
    },
    {
      key: "customerAddress",
      label: "Customer address",
      description: "The mailing address of the customer receiving the invoice.",
      kind: "textarea",
      required: false,
      placeholder: "456 Client Ave, Austin, TX",
      pdfFieldName: "invoice.customer_address",
    },
    {
      key: "invoiceNumber",
      label: "Invoice number",
      description: "The invoice's stable identifying number.",
      kind: "text",
      required: true,
      placeholder: "INV-1001",
      pdfFieldName: "invoice.invoice_number",
    },
    {
      key: "issueDate",
      label: "Issue date",
      description: "The date when the invoice was issued.",
      kind: "date",
      required: true,
      placeholder: "2026-07-19",
      pdfFieldName: "invoice.issue_date",
    },
    {
      key: "dueDate",
      label: "Due date",
      description: "The date when payment is due.",
      kind: "date",
      required: false,
      placeholder: "2026-08-18",
      pdfFieldName: "invoice.due_date",
    },
    {
      key: "currency",
      label: "Currency",
      description: "The currency label or code for the invoice amounts.",
      kind: "text",
      required: true,
      placeholder: "USD",
      pdfFieldName: "invoice.currency",
    },
    {
      key: "subtotal",
      label: "Subtotal",
      description: "The invoice subtotal as a numeric amount.",
      kind: "currency",
      required: true,
      placeholder: "1000",
      pdfFieldName: "invoice.subtotal",
    },
    {
      key: "tax",
      label: "Tax",
      description: "The tax amount as a numeric amount.",
      kind: "currency",
      required: false,
      placeholder: "80",
      pdfFieldName: "invoice.tax",
    },
    {
      key: "total",
      label: "Total",
      description: "The invoice total as a numeric amount.",
      kind: "currency",
      required: true,
      placeholder: "1080",
      pdfFieldName: "invoice.total",
    },
    {
      key: "paymentTerms",
      label: "Payment terms",
      description: "The payment timing or terms for the invoice.",
      kind: "text",
      required: false,
      placeholder: "Net 30",
      pdfFieldName: "invoice.payment_terms",
    },
    {
      key: "notes",
      label: "Notes",
      description: "Additional notes to include on the invoice.",
      kind: "textarea",
      required: false,
      placeholder: "Thank you for your business.",
      pdfFieldName: "invoice.notes",
    },
  ],
  templates: [
    {
      id: "basic-invoice-default",
      label: "Default Basic Invoice",
      assetPath: "templates/basic-invoice-default.pdf",
      flattenByDefault: true,
    },
  ],
} as const);
