import { defineDocument } from "../define-document";

export const jobApplicationDefinition = defineDocument({
  id: "job-application",
  version: 1,
  label: "Job Application",
  description: "A basic employment application with applicant and role details.",
  fields: [
    {
      key: "fullName",
      label: "Full name",
      description: "The applicant's legal or preferred full name.",
      kind: "text",
      required: true,
      placeholder: "Alex Morgan",
      pdfFieldName: "job.full_name",
    },
    {
      key: "email",
      label: "Email address",
      description: "The applicant's primary email address.",
      kind: "email",
      required: true,
      placeholder: "alex@example.com",
      pdfFieldName: "job.email",
    },
    {
      key: "phone",
      label: "Phone number",
      description: "The applicant's primary phone number.",
      kind: "phone",
      required: true,
      placeholder: "+1 555 0100",
      pdfFieldName: "job.phone",
    },
    {
      key: "address",
      label: "Address",
      description: "The applicant's current mailing address.",
      kind: "textarea",
      required: true,
      placeholder: "123 Main St, Springfield, IL",
      pdfFieldName: "job.address",
    },
    {
      key: "currentEmployer",
      label: "Current employer",
      description: "The organization where the applicant currently works.",
      kind: "text",
      required: false,
      placeholder: "Acme Inc.",
      pdfFieldName: "job.current_employer",
    },
    {
      key: "currentJobTitle",
      label: "Current job title",
      description: "The applicant's current job title.",
      kind: "text",
      required: false,
      placeholder: "Operations Manager",
      pdfFieldName: "job.current_job_title",
    },
    {
      key: "yearsOfExperience",
      label: "Years of experience",
      description: "The applicant's total years of relevant experience.",
      kind: "number",
      required: false,
      placeholder: "5",
      pdfFieldName: "job.years_of_experience",
    },
    {
      key: "highestEducation",
      label: "Highest education",
      description: "The applicant's highest completed education level.",
      kind: "text",
      required: false,
      placeholder: "Bachelor's degree",
      pdfFieldName: "job.highest_education",
    },
    {
      key: "positionAppliedFor",
      label: "Position applied for",
      description: "The role or position the applicant is applying for.",
      kind: "text",
      required: true,
      placeholder: "Product Analyst",
      pdfFieldName: "job.position_applied_for",
    },
    {
      key: "availableStartDate",
      label: "Available start date",
      description: "The applicant's earliest available start date.",
      kind: "date",
      required: false,
      placeholder: "2026-08-01",
      pdfFieldName: "job.available_start_date",
    },
    {
      key: "salaryExpectation",
      label: "Salary expectation",
      description: "The applicant's expected salary as a numeric amount.",
      kind: "currency",
      required: false,
      placeholder: "75000",
      pdfFieldName: "job.salary_expectation",
    },
    {
      key: "additionalNotes",
      label: "Additional notes",
      description: "Any additional information the applicant wants to include.",
      kind: "textarea",
      required: false,
      placeholder: "Availability, relocation notes, or portfolio links",
      pdfFieldName: "job.additional_notes",
    },
  ],
  templates: [
    {
      id: "job-application-default",
      label: "Default Job Application",
      assetPath: "templates/job-application-default.pdf",
      flattenByDefault: true,
    },
  ],
} as const);
