export const ERROR_CODES = {
  CORS_ORIGIN_DENIED: "CORS_ORIGIN_DENIED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_JSON: "INVALID_JSON",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  UNKNOWN_SCHEMA: "UNKNOWN_SCHEMA",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
